### ISSUE TITLE
any chance to use this library on Linux with device connected via USB?

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#2] opened 2023-01-11 07:01 UTC
I want to run a lot of (multiplexed, highly automated) long-term measurements within the next years. Windows is completely unfeasible for long-term experiments due to its lack of stability – [even Microsoft knows that](https://lore.kernel.org/lkml/20200914112802.80611-1-wei.liu@kernel.org/T/)... And I also do not want to use the network for controls which are typically somewhat time-critical.

Is there any chance I can control a Zennium device via USB directly? The [remote2 manual](https://doc.zahner.de/manuals/remote2.pdf) says there is a DLL to access the device via USB. I am almost 100 % sure I could get this DLL running under Linux with wine with minimal effort (nowadays, wine is able to run absolutely everything) but as far as I understand, this repository accesses a running instance of the Tahles software via network.

My colleague would also be glad if we can control the Thales software via network but this would not satisfy the needs in my own research project.

I will try to reverse engineer the LabView application in order to find out the usage of `DevCli.dll` but I would also be very glad if Zahner could provide some Python library to control Zennium devices.

**Comment by maxkrapp1** [comment] 2023-01-11 09:36
I think you have misunderstood something.

This Python library does not use the DLL this Python library uses the TCP/IP protocol which is also used by the DLL.

This Python library should run on Linux but we have not tested it ourselves.

The Thales/Term software is a Windows software which is remote controlled by the DLL, Python or raw TCP/IP socket connection over TCP/IP.
On the computer where the Thales/Term is running, the Zennium must be connected with USB. So you could run everything Python on a computer with Linux and then remote control Thales which runs on a Windows computer via TCP/IP. Whether the emulation would work with WINE I am not sure, I have no experience here.

Communicating directly via USB, without the Term software, is not feasible in finite time, in my opinion. The Term software is mandatory as runtime software, which is the terminal emulation for the Thales software running on the Zennium.

**Comment by ilka-schulz** [comment] 2023-01-11 11:26
> Communicating directly via USB, without the Term software, is not feasible in finite time, in my opinion. The Term software is mandatory as runtime software, which is the terminal emulation for the Thales software running on the Zennium.

That is very frustrating, but thanks for the honesty! I am trying to install Thales XT 5.8.4 on my computer for now, but I would really like to not have the user start the term application manually; it would break the automation. Maybe we can take a look at porting the term application to python (or Rust or C++ or anything portable) together in the future. I would be willing to contribute to your code if in return I get a functioning setup ;)

**Comment by maxkrapp1** [comment] 2023-01-11 11:31
Other customers solve the problem by opening and closing the Term on Windows via console and resetting the device via console if necessary. (I have added Windows.)

Remotely, this can be realized via a separate small server, which runs on the computer with Thales and accepts a few commands to start, close and, for example, reset.

**Comment by ilka-schulz** [comment] 2023-01-11 12:12
> Other customers solve the problem by opening and closing the term via console and resetting the device via console if necessary.

I see... Well, I still can not get the Thales XT 5.8.4 software to connect to the potentiostat but I can try your suggested approach.

**Comment by maxkrapp1** [comment] 2023-01-11 15:48
Since the problem is clarified by mail and Linux is only possible under circumstances, I close the ticket.

**Closed as completed by maxkrapp1** 2023-01-11 15:48 UTC
